name: opennesspy
channels:
  - defaults
dependencies:
  - ca-certificates=2019.5.15=0
  - certifi=2019.3.9=py37_0
  - openssl=1.1.1c=he774522_1
  - pip=19.1.1=py37_0
  - python=3.7.3=h8c8aaf0_1
  - setuptools=41.0.1=py37_0
  - sqlite=3.28.0=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_4
  - wheel=0.33.4=py37_0
  - wincertstore=0.2=py37_0
  - pip:
    - pythonnet==2.4.0
prefix: C:\Users\Jonas\.conda\envs\opennesspy

